### ISSUE TITLE
feature request - more options for subunit seection in RMSD

### ISSUE THREAD

**Issue by grandrea** [salilab/imp-sampcon#10]
Hello,

It would be nice if the --subunit option of MasterSamplingExhaustiveness.py supported multiple subunits or residue ranges, perhaps in a syntax symilar to density_ranges.txt. This would allow analysis of cases where movers are disabled in certain parts of the system.

**Comment by grandrea** [comment]
We have implemented this... I can submit a patch if you want

**Comment by benmwebb** [comment]
Sure, pull requests are welcomed!

**Comment by tanmoy7989** [comment]
@grandrea: Can you submit the patch that enables multiple subunits to be passed to the ```---subunit``` option in ```MasterSamplingExhaustiveness.py``` ?

**Comment by grandrea** [comment]
Sorry for the delayed reply, I am a bit too busy these days. Back then, I ended up kind of hard coding the selection into the script as you see here for example. You just need a wrapper that parses it much like density_ranges is parsed... I left the thing half way, but I can finish it later this week finally. So, I regret saying it was done, sorry!

[RMSD_Calculation.py.gz](https://github.com/salilab/imp-sampcon/files/6077507/RMSD_Calculation.py.gz)
