### ISSUE TITLE
pyRMSD's pairwiseRMSDMatrix not taking ambiguity into account

### ISSUE THREAD

**Issue by shruthivis** [salilab/imp-sampcon#17]
Bug report from @jkosinski :

pyRMSD.RMSDCalculator.RMSDCalculator.pairwiseRMSDMatrix and thus get_rmsds_matrix does not really take ambiguity into account, while pyRMSD.RMSDCalculator.RMSDCalculator.oneVsFollowing does.

As a test, I prepared two RMF files of a complex, three proteins, two copies each. The two files are almost identical, but chains of one protein are swapped. But from imp-sampcon and pairwiseRMSDMatrix I get rmsd of 114A. From oneVsFollowing I get rmsd of 2A.

See test case and script here:
https://oc.embl.de/index.php/s/NhFYx12ebbKe0v1

@ichem001 I think you are the expert here. Can you please help with this?

**Comment by jkosinski** [comment]
@ichem001 if it helps:
I seem to get ambiguity taken into account by the imp-sampcon script if in get_rmsds_matrix of rmsd_calculation.py I replace:
```
    rmsd = calculator.pairwiseRMSDMatrix()
```
with
```
    rmsd = []
    for i in range(len(conforms)-1):
        rmsd.extend(calculator.oneVsFollowing(i))
```

**Comment by ichem001** [comment]
@jkosinski 

I have tried to reproduce your error but I am not able to reproduce either of the values. 

1. Produce the smallest possible example that shows the error. It does not make sense to debug on a six subunits complex. 
2. Could you run the `test_rmsd_calculation.py` test and make sure it passes. That test also makes sure you are using the latest version of `imp-sampcom`. 
3. I cannot reproduce your numbers. I get a RMSD of 76 Å, not of 114 Å. 

Let's take it from here to try to understand what the issue is.

**Comment by jkosinski** [comment]
Hi Ilan,

Thanks for looking into this!

1.  Sure, taking your usual structure as an example, building a dimer, and saving two RMF files with identical coordinates but with swapped chains (RMSD should be 0.0 when ambiguity works):
```python
import IMP
import IMP.atom
import IMP.rmf
import IMP.pmi
import IMP.pmi.topology
import RMF
import sys


random_tr3d = IMP.algebra.get_random_local_transformation([0,0,0], 10, 10)


#create two swapped files
for file_i in (0, 1):
    seqs = IMP.pmi.topology.Sequences(IMP.pmi.get_example_path('data/1WCM.fasta'))
    mdl = IMP.Model()
    s = IMP.pmi.topology.System(mdl)
    st = s.create_state()

    #add t
    mol = st.create_molecule("Rpb4", seqs["1WCM:D"], chain_id="D")

    atomic = mol.add_structure(IMP.pmi.get_example_path('data/1WCM_fitted.pdb'),
                        chain_id="D")

    mol.add_representation(
     atomic,
     resolutions=[1])

    clone = mol.create_clone("E")

    hier = s.build()

    if file_i == 0:
        #for the first file, transform the copy 0
        IMP.atom.transform(mol.get_hierarchy(), random_tr3d)
    else:
        #for the second file, transform the copy 1
        IMP.atom.transform(clone.get_hierarchy(), random_tr3d)

    orh = RMF.create_rmf_file('{0}.rmf3'.format(file_i))
    IMP.rmf.add_hierarchy(orh, s.get_hierarchy())
    IMP.rmf.save_frame(orh)
    del orh


#calculate RMSDs

import pyRMSD
from pyRMSD.matrixHandler import MatrixHandler
import scipy
import scipy.spatial
from IMP.sampcon import rmsd_calculation

symmetry = "symm_groups.txt"
with open(symmetry, 'w') as f:
    f.write('Rpb4.0 Rpb4.1')

###########################################
#  reproducing what imp-exhaust is doing: #
###########################################

(ps, masses, radii,
 conforms, symm_groups, models_name,
 n_models) = rmsd_calculation.get_rmfs_coordinates_one_rmf(
     "./",
     '0.rmf3',
     '1.rmf3',
     None,
     symmetry)

rmsd_calculation.get_rmsds_matrix(  # noqa
    conforms, 'cpu_omp', False, 2, symm_groups)

mHandler = MatrixHandler()
mHandler.loadMatrix("Distances_Matrix.data")

rmsd_matrix = mHandler.getMatrix()
distmat = rmsd_matrix.get_data()

distmat_full = scipy.spatial.distance.squareform(distmat)
print('RMSD from get_rmsds_matrix', distmat_full[0,1]) #this should be 0.0 Angstrom but is not !

###############################
# let's try differently then: #
###############################

calculator = pyRMSD.RMSDCalculator.RMSDCalculator(
  'NOSUP_OMP_CALCULATOR',
  fittingCoordsets=conforms,
  calcSymmetryGroups=symm_groups,
  fitSymmetryGroups=symm_groups)

rmsd = calculator.oneVsFollowing(0)[0]
print('RMSD from calculator.oneVsFollowing(0)', rmsd) # now it works, is 0.0 Angstrom !

#but rmsd from pairwiseRMSDMatrix() is still wrong!:
print('RMSD from calculator.pairwiseRMSDMatrix',calculator.pairwiseRMSDMatrix()[0])

###############################
# let's try without ambiguity: #
###############################
calculator = pyRMSD.RMSDCalculator.RMSDCalculator(
  'NOSUP_OMP_CALCULATOR',
  fittingCoordsets=conforms)

rmsd = calculator.oneVsFollowing(0)[0]
print('RMSD from calculator.oneVsFollowing(0) WITHOUT AMBUIGUITY', rmsd) # without ambiguity, the same value as from get_rmsds_matrix!

#but rmsd from pairwiseRMSDMatrix() is still wrong!:
print('RMSD from calculator.oneVsFollowing(0) WITHOUT AMBUIGUITY', calculator.pairwiseRMSDMatrix()[0]) # same here
```
2. Yes, passes.
3. Hmm, strange, I think Shruthi said she could reproduce. Still, with ambiguity should be much lower than 76A.

**Comment by shruthivis** [comment]
With the previous version of Jan's script [pyRMSD_bug.zip](https://github.com/salilab/imp-sampcon/files/6916182/pyRMSD_bug.zip)
I could reproduce the numbers 2 A and 114 A. Looks like the script changed to include a selection.

**Comment by jkosinski** [comment]
I think I introduced the selection after Ilan's email, so its weird he got
different values.

I added the selection to narrow down the issue to the Elp2 subunit, but
that script is not that important anymore with the new example i posted.
