### ISSUE TITLE
Suspected bug or historical reasons? for choosing either pval or cvs in clustering_rmsd.py at Line 194

### ISSUE THREAD

**Issue by neeleshsoni21** [salilab/imp-sampcon#39]
Is there a historical reason for choosing satisfaction of either p-value or Cramer's v? Ideally, both should be satisfied. 

The OR condition at Line 194 in clustering_rmsd.py chooses satisfaction of only one not both. "  if pvals[i] > 0.05 or cvs[i] < 0.10:  "
[prot1.ChiSquare.pdf](https://github.com/user-attachments/files/16238631/prot1.ChiSquare.pdf)
[prot1.ChiSquare_Grid_Stats.txt](https://github.com/user-attachments/files/16238658/prot1.ChiSquare_Grid_Stats.txt)

In the attached figure, the p-value was ignored, and the selection was made based on Cramer's V and clustered population.

Context:
File: clustering_rmsd.py
Line Number: 194
Link to Line: [clustering_rmsd.py](https://github.com/salilab/imp-sampcon/blob/ecba92f/pyext/src/clustering_rmsd.py#L194)

If this is a bug, the suggested fix is that OR should be changed to AND at Line 194 in clustering_rmsd.py.

 if pvals[i] > 0.05 and cvs[i] < 0.10:

**Comment by shruthivis** [comment]
This seems to be fine and not a bug. See the sampcon paper doi:
10.1016/j.bpj.2017.10.005 section on "Clustering models using several
thresholds".

The two samples are said to have the same model distribution if the p-value
from this test is insignificant (pval >0.05) or it is significant but the
magnitude of the difference is small (cramer V < 0.1).
In the example shown, the sampling precision is 70 A as it is the smallest
distance at which >80% of the population has the same model distribution
according to the previous statement. Happy to chat in details offline.

**Comment by neeleshsoni21** [comment]
For clarity, I will name the two conditions as 1 and 2: The two samples are said to have the same model distribution if 
Condition 1: the p-value from this test is insignificant (pval >0.05) 
OR
Condition 2: if it is significant (pval < 0.05) but the magnitude of the difference is small (Cramer's V < 0.1)

However, due to condition 2, the precision values would be very different than originally shown in the paper. For example: In Sampcon paper 10.1016/j.bpj.2017.10.005

Figure S1 (C) should have precision around ~5A  (p-value < 0.05 & Cramer's V < 0.1). But instead, it was set at ~10A 
<img width="366" alt="image" src="https://github.com/user-attachments/assets/84830e00-d09f-4bc2-b1d3-a4fa506d600c">


Figure S2 (C) should have precision around ~10A (p-value < 0.05 & Cramer's V < 0.1). But instead, it was set at ~16A 
<img width="349" alt="image" src="https://github.com/user-attachments/assets/d08908fc-e60b-4c73-98a9-b3274c557dc3">

Similarly, for Figures 3, S3, and S4. All of the figures make sense if all three conditions are true together.

I will schedule a meeting with you in a few days to discuss this in detail. Thank you

**Comment by shruthivis** [comment]
I see the confusion. The protocol implementation for the BJ 2017 paper (at
salilab.org/sampcon) is slightly different and more conservative than the
current imp-sampcon implementation (at github.com/salilab/imp-sampcon).
This was also noted by another user earlier and had led to the update of
the README of the sampcon module to state this explicitly (see `Minor
updates to the protocol from the BJ paper` part of the README).

This is the correct criterion: samples A and B can be considered as coming
from the same distribution of structures if (a) the p-value is not
significant. Or (b) even though the p-value is significant, effect size is
small (Cramer's V). The idea is that even small differences can show up as
significant by p-value if the number of models is large. So we use an
effect size to additionally check if the magnitude of the difference is
large when the difference shows up as significant. The distributions are
considered effectively the same if (a) or (b) hold, and additionally,
atleast 80% of the models need to be in clusters. So it is implemented in
the current code as an "or". You can see a similar description of this
p-value + effect size consideration in the BJ paper in the "Similarity of
Scores" section. Basically, the "AND" implementation in the sampcon paper
is slightly more stringent than the currently used "OR" implementation. The
latter would lead to lower (better) precision estimates than the former.

**Comment by neeleshsoni21** [comment]
Thank you for the clarification. It appears that the issue originates from the tutorial text, which needs to be updated according to the minor update in the protocol. I have opened the issue in the [actin_tutorial](https://github.com/salilab/actin_tutorial/issues/5) to modify the tutorial text with the correct criterion. Closing this issue now.
